config/routes.rb
Rails.application.routes.draw do
  root 'messages#index'
  resources :messages , except: [:index, :new]

end

app/models/message.rb
class Message < ActiveRecord::Base
  # 名前は必須入力かつ20文字以内
  validates :name , length: { maximum: 20 } , presence: true
  # 内容は必須入力かつ2文字以上30文字以下
  validates :body , length: { minimum: 2, maximum: 30 } , presence: true
  # 年齢は必須入力かつ0以上200未満の数字
  validates :age , numericality: { only_integer: true, greater_than: 0, less_than_or_equal_to: 200 } , presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:edit, :update, :destroy]
  
  def index
    @message = Message.new
    # Messageを全て取得する。
    @messages = Message.all
  end

  def create
    @message = Message.new(message_params)
    if @message.save
      redirect_to root_path , notice: 'メッセージを保存しました'
    else
      # メッセージが保存できなかった時
      @messages = Message.all
      flash.now[:alert] = "メッセージの保存に失敗しました。"
      render 'index'
    end
  end
  
  def edit
  end
  
  def update
    if @message.update(message_params)
      # 保存に成功した場合はトップページへリダイレクト
      redirect_to root_path , notice: 'メッセージを編集しました'
    else
      # 保存に失敗した場合は編集画面へ戻す
      render 'edit'
    end
  end
  
  def destroy
    @message.destroy
    redirect_to root_path, notice: 'メッセージを削除しました'
  end
  
  private
  def message_params
    params.require(:message).permit(:name, :body, :age)
  end
  
  def set_message
    @message = Message.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MessageBoard</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar">
    <div class="container">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">Message Board</a>
      </div>
    </div>
  </nav>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/messages/_form.html.erb
<%= form_for(@message, html: { class: "form-horizontal" }) do |f| %>
  <% if @message.errors.present? %>
    <div class="alert alert-danger">
      <%= alert %>
      <ul>
        <% @message.errors.full_messages.each do |full_message| %>
          <li>
            <%= full_message %>
          </li>
        <% end %> 
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label for="message_name" class="col-sm-2 control-label">名前</label>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control", placeholder: "名前を記入して下さい" %>
    </div>
  </div>
  
  <div class="form-group">
    <label for="message_body" class="col-sm-2 control-label">内容</label>
    <div class="col-sm-10">
      <%= f.text_area :body, class: "form-control", placeholder: "内容を記入して下さい" %>
    </div>
  </div>
  
    <div class="form-group">
    <label for="message_age" class="col-sm-2 control-label">年齢</label>
    <div class="col-sm-10">
      <%= f.number_field :age, class: "form-control" %>
    </div>
  </div>
  
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-sm btn-primary" %>
    </div>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>メッセージの編集</h1>

<%= render 'form' %>

app/views/messages/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    メッセージ一覧
  </div>
    
  <div class="panel-body">
    <% @messages.each do |message| %>
      <span class="label label-info"><%= message.name %></span>
      <%= message.body %>
      <%= message.age %>
      (<%= link_to "edit" , edit_message_path(message) %>)
      (<%= link_to "destroy" , message , method: :delete, data: { confirm: '削除してもよろしいですか？'} %>)
      <br>
    <% end %>
  </div>
</div>

<% #部分テンプレートを読み込んでいる %>
<%= render 'form' %>